Update patch set 3
Patch Set 3:

src/UpnpWanCommonInterfaceConfigService.cpp
src/UpnpWanCommonInterfaceConfigService.cpp: In static member function 'static void UpnpWanCommonInterfaceConfig::getLinkPropertiesCb(GUPnPServiceProxy*, GUPnPServiceProxyAction*, gpointer)':
src/UpnpWanCommonInterfaceConfigService.cpp:122:55: error: cannot pass objects of non-trivially-copyable type 'std::string {aka class std::basic_string<char>}' through '...'
                                                   NULL);
                                                       ^
src/UpnpWanCommonInterfaceConfigService.cpp:122:55: error: cannot pass objects of non-trivially-copyable type 'std::string {aka class std::basic_string<char>}' through '...'
scons: *** [out/linux/x86_64/release/obj/bridge/UpnpWanCommonInterfaceConfigService.os] Error 1
scons: building terminated because of errors.

Patch-set: 3